name: playground
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.4.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  rxdart: ^0.27.5
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  built_value_generator: ^8.4.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
